# Generated by Django 4.0.6 on 2022-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True, verbose_name='Заказ №')),
                ('dollar_cost', models.FloatField(verbose_name='Стоимость, $')),
                ('ruble_cost', models.FloatField(verbose_name='Стоимость, Р')),
                ('date_finish', models.DateField(verbose_name='Дата поставки')),
            ],
        ),
    ]
